### ISSUE TITLE
BUG: Attempting to read in .dream3d files from previous versions of DREAM.3D (below version 7.0.0) causes DREAM.3D to close out.

### ISSUE THREAD

**Issue by StopkaKris** [BlueQuartzSoftware/DREAM3DNX-Issues#9]
### Is there an existing issue for this?

- [X] I have searched the existing issues, known issues in release notes, and documentation.

### Brief Description of the Issue and Expected Behavior

Hello,

I realize that the structure of .dream3d files likely changed for DREAM.3D NX, but I wanted to see if I could open a .dream3d file saved in version 6.5.141 and 6.5.171 using DREAM.3D NX. In both cases, DREAM.3D NX crashes. Perhaps there should instead be an error message that is provided to the user, after the software checks whether the .dream3d file is has been saved in the older or newer format?

Best regards,
Krzysztof Stopka

### Version

other (Please enter in the extended description at the bottom)

### What operating system are you seeing the problem on? [Further details may be required during triage process]

Windows 10

### What section did you encounter the error in? [Further details may be required during triage process]

GUI client

### Steps To Reproduce

This bug can be replicated using DREAM3DNX Version 7.0.0-RC-10 running on Windows 10.

Open using DREAM3DNX.exe, then select the "Read DREAM.3D File" filter. Click the "select" button and navigate to a .dream3d file from an older version of DREAM.3D.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nyoungbq** [comment]
Hello Krzysztof,

I am one of the developers for DREAM3DNX at BlueQuartz Software and I have reached out to the rest of the team about your issue! I will be happy to look into this further for you. I know we do support some backwards compatibility in the underlying library with the unstable branch of old DREAM.3D (6.6.x). However, I believe that compatibility extends to the later versions of 6.5.x, but I can't confirm that without discussing with the team. I agree it definitely should not be crashing either way.

I will look into this further as soon as I get in tomorrow. If you could provide me a copy of the pipeline causing the crash that would really help. If you are unable to provide the specific pipeline, it would be helpful if you could make a similar pipeline that causes the issue or provide one of our default pipelines that cause the crash. If you are unable to do so I can try to replicate it myself with some of the default pipelines, but I at the current time I am unsure if this will cause the crash since chances are it is a specific filter's parameters.

It is also possible that one of the filters in your pipeline are not included in the 7.0.0 version (DREAM3DNX) at the current time. If it contains any filters from the synthetic plugin this could be the case, since we have not brought those codes across to the latest version yet.

Regardless, thank you for taking the time to report this issue and better the usability! The team here will do the best we can to isolate and fix it.

Respectfully,
Nathan

**Comment by imikejackson** [comment]
@StopkaKris Does your .dream3d file have any synthetic data containers specifically where the stats data array is held. NOT the actual generated microstructure, but the stats that go into the creation of the microstructure. If so there is a current issue that we are trying to solve with this.

I'll get something up on the web site in a bit to address this.

**Comment by StopkaKris** [comment]
Hi Nathan and Mike,

Thank you for the quick response. Indeed, the issue was that the .dream3d file I was attempting to read in contained the ```StatsGeneratorDataContainer``` in ```DataContainers```. I used [HDFView](https://www.hdfgroup.org/downloads/hdfview/) to delete ```StatsGeneratorDataContainer``` and I can now read in the .dream3d file with no problems. Please feel free to close this issue.

Best regards,
Krzysztof Stopka
